services:
  mysql:
    image: mysql:8.0
    container_name: mushroom_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: mushroom_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mushroom_api
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: "123"
      DB_NAME: mushroom_db
      DB_PORT: "3306"
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: mushroom_streamlit
    restart: always
    environment:
      API_BASE_URL: http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  mysql_data: